apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim.fullname" . }}
  labels:
    {{- include "valheim.labels" . | nindent 4 }}
  {{- with .Values.headlessService.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.headlessService.type }}
  clusterIP: None
  ports:
    - name: server-port
      port: {{ .Values.valheimDedicatedServer.port }}
      targetPort: server-port
      protocol: UDP
    - name: query-port
      port: {{ add .Values.valheimDedicatedServer.port 1 }}
      targetPort: query-port
      protocol: UDP
  selector:
    {{- include "valheim.selectorLabels" . | nindent 4 }}
