{{- range $i, $instance := .Values.instances }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim.fullname" $ }}-{{ $i }}
  labels:
    {{- include "valheim.labels" $ | nindent 4 }}
  {{- with $instance.service.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $instance.service.type }}
  externalTrafficPolicy: {{ $instance.service.externalTrafficPolicy }}
  ports:
    - name: server-port
      port: {{ $.Values.valheimDedicatedServer.port }}
      targetPort: server-port
      protocol: UDP
    - name: query-port
      port: {{ add $.Values.valheimDedicatedServer.port 1 }}
      targetPort: query-port
      protocol: UDP
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "valheim.fullname" $ }}-{{ $i }}
---
{{- end }}